#' autotest_rectangular
#'
#' Automatically test a variety of rectangular objects as inputs to functions
#' specified in a 'yaml' template.
#'
#' @param yaml A 'yaml' template as a character vector, either hand-coded or
#' potentially loaded via \link{readLines} function or similar. Should generally
#' be left at default of 'NULL', with template specified by 'filename'
#' parameter.
#' @param filename Name (potentially including path) of file containing 'yaml'
#' template. See \link{at_yaml_template} for details of template. Default uses
#' template generated by that function, and held in local './tests' directory.
#' @param quiet If 'FALSE', provide printed output on screen.
#' @return Nothing
#' @export
autotest_rectangular <- function (yaml = NULL, filename = NULL, quiet = FALSE) {
    res <- parse_yaml_template (yaml = yaml, filename = filename)

    . <- NULL # suppress no visible binding note

    if (!quiet)
        message (cli::symbol$star, " Testing functions:")

    for (i in seq (res$parameters)) {
        this_fn <- names (res$parameters) [i]

        if (!quiet)
            cli::cli_ul (this_fn)

        params <- get_params (res, i, this_fn)

        #out <- do.call (this_fn, params)
        rect_index <- which (vapply (params, function (i)
                                     length (dim (i)) == 2, logical (1)))
        for (r in rect_index) {
            x <- params [[r]]
            params_r <- params

            params_r [[r]] <- data.frame (x)
            res1 <- do.call (this_fn, params_r)

            params_r [[r]] <- tibble::tibble (x)
            res2 <- do.call (this_fn, params_r)

            params_r [[r]] <- data.table::data.table (x)
            res3 <- do.call (this_fn, params_r)

            testthat::expect_identical (res1, res2)
            testthat::expect_identical (res1, res3)

            # extended class structure should still work:
            params_r [[r]] <- structure (x, class = c ("newclass", class (x)))
            res4 <- do.call (this_fn, params_r)
            testthat::expect_identical (res1, res4)

            # new class structure which exposes 'List` structure of `data.frame`
            # and should generally fail:
            params_r [[r]] <- structure (x, class = c ("newclass"))
            testthat::expect_error (do.call (this_fn, params_r))
        }
    }
}
