#' autotest
#'
#' Automatically test inputs to functions specified in a 'yaml' template.
#'
#' @param yaml A 'yaml' template as a character vector, either hand-coded or
#' potentially loaded via \link{readLines} function or similar. Should generally
#' be left at default of 'NULL', with template specified by 'filename'
#' parameter.
#' @param filename Name (potentially including path) of file containing 'yaml'
#' template. See \link{at_yaml_template} for details of template. Default uses
#' template generated by that function, and held in local './tests' directory.
#' @param quiet If 'FALSE', provide printed output on screen.
#' @return Nothing
#' @export
autotest <- function (yaml = NULL, filename = NULL, quiet = FALSE) {

    res <- parse_yaml_template (yaml = yaml, filename = filename)

    if (!quiet)
        message (cli::col_green (cli::symbol$star, " Testing functions:"))

    for (i in seq (res$parameters)) {
        this_fn <- names (res$parameters) [i]

        params <- get_params (res, i, this_fn)
        classes <- res$classes [[i]]

        chk1 <- autotest_rectangular (params, this_fn, classes, quiet)
        chk2 <- autotest_vector (params, this_fn, classes, quiet)

        chk3 <- autotest_return (res$package, params, this_fn)

        if (chk1 && chk2 && chk3)
            message (cli::col_green (cli::symbol$tick, " ", this_fn))
        else
            message (cli::col_red (cli::symbol$cross), " ", cli::col_yellow (this_fn))
    }
}


autotest_rectangular <- function (params, this_fn, classes, quiet) {

    chk <- TRUE # Not implemented; TODO: Implement
    
    rect_index <- which (vapply (params, function (i)
                                 length (dim (i)) == 2, logical (1)))
    for (r in rect_index) {
        x <- params [[r]]
        params_r <- params

        params_r [[r]] <- data.frame (x)
        res1 <- do.call (this_fn, params_r)

        params_r [[r]] <- tibble::tibble (x)
        res2 <- do.call (this_fn, params_r)

        params_r [[r]] <- data.table::data.table (x)
        res3 <- do.call (this_fn, params_r)

        testthat::expect_identical (res1, res2)
        testthat::expect_identical (res1, res3)

        # Modify class definitions for rectangular inputs if not excluded by
        # yaml class definitions
        if (!names (params_r) [rect_index [r]] %in% names (classes)) {
            # extended class structure should still work:
            params_r [[r]] <- structure (x, class = c ("newclass", class (x)))
            res4 <- do.call (this_fn, params_r)
            testthat::expect_identical (res1, res4)

            # new class structure which exposes 'List` structure of `data.frame`
            # and should generally fail:
            params_r [[r]] <- structure (x, class = c ("newclass"))
            testthat::expect_error (do.call (this_fn, params_r))
        } else {
            # TODO: Implement check for all nominated classes
        }
    }
    return (chk)
}

autotest_vector <- function (params, this_fn, classes, quiet) {

    chk <- TRUE

    null_params <- NULL
    if (any (params == "NULL")) {
        null_params <- params [params == "NULL"]
        params <- params [params != "NULL"]
    }

    vec_index <- which (vapply (params, function (i)
                                length (i) > 1 && is.null (dim (i)), logical (1)))
    for (v in vec_index) {
        params_v <- params

        res1 <- tryCatch (do.call (this_fn, params_v),
                          warning = function (w) w)
        warn <- FALSE
        if (methods::is (res1, "warning")) {
            cli::cli_text (cli::col_yellow ("function [", this_fn,
                                            "] issued a Warning: ",
                                            res1$message))
            warn <- TRUE
            res1 <- suppressWarnings (do.call (this_fn, params_v))
        }

        # int columns submitted as double should return different result:
        if (typeof (params_v [[v]]) == "integer") {
            params_v [[v]] <- as.numeric (params_v [[v]])
            if (warn)
                res2 <- suppressWarnings (do.call (this_fn, params_v))
            else
                res2 <- do.call (this_fn, params_v)
            testthat::expect_true (!identical (res1, res2))
            params_v <- params
        }

        # class definitions for vector columns should be ignored
        if (!names (params_v) [vec_index [v]] %in% names (classes)) {
            x <- params_v [[v]]
            class (x) <- "different"
            params_v [[v]] <- x
            res3 <- tryCatch (
                              do.call (this_fn, params_v),
                              warning = function (w) w,
                              error = function (e) e)
            if (methods::is (res3, "error")) {
                chk <- FALSE
                warning ("Function [", this_fn, "] errors on vector columns with ",
                         "different classes when submitted as ", names (params) [v],
                         "\n  Error message: ", res3$message,
                         call. = FALSE, immediate. = TRUE)
            } else {
                # TODO: Expectation - they need not be identical, because class
                # def may be carried over to result
                #expect_identical (res1, res3)
            }
            params_v <- params
        } else {
            # TODO: Implement check for all nominated classes
        }

        # List-columns
        x <- params_v [[v]]
        x <- I (as.list (x))
        params_v [[v]] <- x
        res4 <- tryCatch (
                          do.call (this_fn, params_v),
                          warning = function (w) w,
                          error = function (e) e)
        if (methods::is (res4, "error")) {
            chk <- FALSE
            warning ("Function [", this_fn, "] errors on list-columns ",
                     "when submitted as ", names (params) [v],
                     "\n  Error message: ", res4$message,
                     call. = FALSE, immediate. = TRUE)
        } else {
            # TODO: Expectation here too
            #expect_identical (res1, res4)
        }
    }

    return (chk)
}

autotest_return <- function (pkg, params, this_fn) {

    chk <- TRUE

    retval <- tryCatch (
                        do.call (this_fn, params),
                        warning = function (w) w)
    if (methods::is (retval, "warning")) {
        cli::cli_text (cli::col_yellow ("Function [", this_fn,
                                        "] issued a Warning: ",
                                        retval$message))
        retval <- suppressWarnings (do.call (this_fn, params))
    }

    if (!is.null (attr (retval, "class"))) {
        Rd_value <- get_Rd_value (package = pkg, fn_name = this_fn)
        if (is.null (Rd_value)) {
            chk <- FALSE
            warning ("Function [", this_fn, "] does not specify a return value, ",
                     "yet returns a value of class [", attr (retval, "class"), "]",
                     call. = FALSE, immediate. = TRUE)
        } else {
            chk <- grepl ("[Cc]lass", Rd_value)
            if (!chk)
                warning ("Function [", this_fn, "] does not specify class of return value, ",
                         "yet returns a value of class [", attr (retval, "class"), "]",
                         call. = FALSE, immediate. = TRUE)
        }
    }

    return (chk)
}
